fos_chat:
    db_driver: # orm | mongodb
    thread_class: # App\Entity\ChatThread | App\Document\Thread
    message_class: # App\Entity\ChatMessage | App\Document\Message
    spam_detector: # akismet